[package]
name = "four-one-one"
version = "0.1.0"
authors = ["t1ra <t1ra@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.1"